// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpswmiolrywnvwfhijaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwc3dtaW9scnl3bnZ3ZmhpamF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjMwNDQsImV4cCI6MjA3MDczOTA0NH0.Lvg-2lHofbirU7zW6-aEc_Wms_CDaoFLi6T33nxh6Oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});